pythonProject/projeto_estoque/app_estoque/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #rota,view responsavel, nome de referencia
    path('', views.home, name='home'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    path('record/<int:pk>', views.customer_record, name='record'),
    path('delete_record/<int:pk>', views.delete_record, name='delete_record'),
    path('add_record/', views.add_record, name='add_record'),
    path('update_record/<int:pk>', views.update_record, name='update_record'),


]+static(settings.STATIC_URL,docment_root=settings.STATIC_ROOT)

pythonProject/projeto_estoque/projeto_estoque/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    #rota,view responsavel, nome de referencia
    path('admin/', admin.site.urls),
    path('', include('app_estoque.urls')),
]

pythonProject/projeto_estoque/app_estoque/models.py
from django.db import models

class Record(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    nome = models.CharField(max_length=50)
    sobrenome = models.CharField(max_length=50)
    cep = models.CharField(max_length=8)
    logradouro = models.CharField(max_length=50)
    cidade = models.CharField(max_length=50)
    estado = models.CharField(max_length=50)
    email = models.CharField(max_length=100)
    telefone = models.CharField(max_length=15)


def __str__(self):
    return(
        f"{self.nome} {self.sobrenome}"
    )

pythonProject/projeto_estoque/app_estoque/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Record
from .utils import get_address_info
import requests



class SignUpForm(UserCreationForm):
	email = forms.EmailField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Email Address'}))
	first_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'First Name'}))
	last_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Last Name'}))


	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')


	def __init__(self, *args, **kwargs):
		super(SignUpForm, self).__init__(*args, **kwargs)

		self.fields['username'].widget.attrs['class'] = 'form-control'
		self.fields['username'].widget.attrs['placeholder'] = 'Nome do Usuário'
		self.fields['username'].label = ''
		self.fields['username'].help_text = '<span class="form-text text-muted"></span>'

		self.fields['password1'].widget.attrs['class'] = 'form-control'
		self.fields['password1'].widget.attrs['placeholder'] = 'Password'
		self.fields['password1'].label = ''
		self.fields['password1'].help_text = '<ul class="form-text text-muted small"><li>Sua senha não pode ser semelhante informações pessoais.</li><li>Sua senha deve conter pelo menos 8 caracteres.</li><li>Sua senha não pode ser igual a anterior.</li><li>Sua senha deve conter letras e numeros.</li></ul>'

		self.fields['password2'].widget.attrs['class'] = 'form-control'
		self.fields['password2'].widget.attrs['placeholder'] = 'Confirma senha'
		self.fields['password2'].label = ''
		self.fields['password2'].help_text = '<span class="form-text text-muted"></span>'

class AddRecordForm(forms.ModelForm):
	nome = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={"placeholder":"nome","class":"form-control"}),label="Nome")
	sobrenome = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={"placeholder":"sobrenome","class":"form-control"}),label="Sobrenome")
	cep = forms.CharField(required=True,widget=forms.widgets.TextInput(attrs={"placeholder": "CEP", "class": "form-control"}),label="Cep")
	logradouro = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={"placeholder":"endereco","class":"form-control"}),label="Logradouro")
	cidade = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={"placeholder":"cidade","class":"form-control"}),label="Cidade")
	estado = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={"placeholder":"estado","class":"form-control"}),label="Estado")
	email = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={"placeholder":"email","class":"form-control"}),label="Email")
	telefone = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={"placeholder":"telefone","class":"form-control"}),label="Telefone")

	def clean_cep(self):
		cep = self.cleaned_data.get('cep')
		address_info = get_address_info(cep)
		if not address_info:
			raise forms.ValidationError('CEP inválido')
		return cep

	class Meta:
		model = Record
		exclude = ("user",)

pythonProject/projeto_estoque/app_estoque/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login,logout
from django.contrib import messages
from .forms import SignUpForm,AddRecordForm
from .models import Record
import requests

def home(request):
	filtro_nome = request.GET.get('filtro_nome')

	# Se houver um parâmetro de filtro de nome na URL
	if filtro_nome:
		# Ajuste a consulta para filtrar os funcionários pelo nome
		records = Record.objects.filter(nome__icontains=filtro_nome)
		return render(request, 'usuario/home.html', {'records': records})
#Verificar Loggin
	if request.method == 'POST':
		username=request.POST['username']
		password=request.POST['password']
		#Autenticar login
		user = authenticate(request, username=username, password=password)
		if user is not None:
			login(request, user)
			messages.success(request,"Voce esta logado!")
			return redirect('home')
		else:
			messages.success(request,"Usuario ou Senha incorreto, Tente Novamente!")
			return redirect('home')
	else:
		records = Record.objects.all()
		return render(request,'usuario/home.html',{'records':records})

#def login_user(request):
    #pass
def logout_user(request):
    logout(request)
    messages.success(request, "Usuario Desconectado")
    return redirect('home')

def register_user(request):
	if request.method == 'POST':
		form = SignUpForm(request.POST)
		if form.is_valid():
			form.save()
			# Authenticate and login
			username = form.cleaned_data['username']
			password = form.cleaned_data['password1']
			user = authenticate(username=username, password=password)
			login(request, user)
			messages.success(request, "Registrado com sucesso! Bem-vindo!")
			return redirect('home')
	else:
		form = SignUpForm()
		return render(request, 'usuario/register.html', {'form':form})

	return render(request, 'usuario/register.html', {'form':form})


def customer_record(request, pk):
    if request.user.is_authenticated:
        # Look Up Records
        customer_record = Record.objects.get(id=pk)
        return render(request, 'usuario/record.html', {'customer_record': customer_record})
    else:
        messages.success(request, "Você deve estar logado para visualizar essa página!")
        return redirect('home')

def delete_record(request, pk):
	if request.user.is_authenticated:
		delete_it = Record.objects.get(id=pk)
		delete_it.delete()
		messages.success(request, "Deletado com Sucesso")
		return redirect('home')
	else:
		messages.success(request, "Você deve estar logado para visualizar essa página!")
		return redirect('home')
def add_record(request):
	form = AddRecordForm(request.POST or None)
	if request.user.is_authenticated:
		if request.method == "POST":
			if form.is_valid():
				add_record = form.save()
				messages.success(request, "Cadastrado com Sucesso!")
				return redirect('home')
		return render(request, 'usuario/add_record.html', {'form':form})
	else:
		messages.success(request, "Você deve estar logado para visualizar essa página!")
		return redirect('home')
def update_record(request, pk):
	if request.user.is_authenticated:
		current_record = Record.objects.get(id=pk)
		form = AddRecordForm(request.POST or None, instance=current_record)
		if form.is_valid():
			form.save()
			messages.success(request,"Registro atualizado")
			return redirect('home')
		return render(request, 'usuario/update_record.html', {'form': form})
	else:
		messages.success(request, "Você deve estar logado para visualizar essa página!")
		return redirect('home')

pythonProject/projeto_estoque/app_estoque/templates/usuario/add_record.html
{% extends 'usuario/base.html' %}

{% block content %}
<div class="col-md-6 offset-md-3">
    <h1>Cadastro de Funcionário</h1>
    <br/>
    <form method="POST" action="{% url 'add_record' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <br/>
        <button type="submit" class="btn btn-secondary">Adicionar</button>
        <a href="{% url 'home' %}" class="btn btn-secondary">Voltar</a>
    </form>
               <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script>
        $(document).ready(function() {
            $('#id_cep').change(function() {
                var cep = $(this).val();
                $.ajax({
                    url: 'https://viacep.com.br/ws/' + cep + '/json/',
                    dataType: 'json',
                    success: function(data) {
                        $('#id_logradouro').val(data.logradouro);
                        $('#id_bairro').val(data.bairro);
                        $('#id_cidade').val(data.localidade);
                        $('#id_estado').val(data.uf);
                    }
                });
            });
        });
        </script>
</div>
{% endblock %}

pythonProject/projeto_estoque/app_estoque/templates/usuario/base.html
<!doctype html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Controle de funcionarios-RH</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
      <!-<link href="{{STATIC_URL}}app_estoque/styles/styles.css" rel="stylesheet">
  </head>
  <body>
    {% include 'usuario/navbar.html' %}
    <div class="container">
        <br/>
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-warning alert-dismissible fade show red " role="alert">
                    {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}

        {% block content %}
        {% endblock %}

    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

pythonProject/projeto_estoque/app_estoque/templates/usuario/home.html
{% extends 'usuario/base.html' %}

{% block content %}
    {% if user.is_authenticated %}

        <form class="d-table-row" method="GET" action="{% url 'home' %}">
            <div class="mb-4 d-flex">
                <input type="text" class="form-control" name="filtro_nome"  placeholder="Filtrar por nome">
                <button type="submit" class="btn btn-outline-success" >Filtrar</button>
                <a href="{% url 'home' %}" class="btn btn-secondary">Voltar</a>
            </div>
        </form>
            <div class=" ">
                <a class="btn btn-secondary " href="{%url 'add_record'%}">Cadastrar Funcionario</a>
            </div>
<br>
        <table class="table table-bordered ">
            <thead class="table table-dark table-hover ">
                <tr>
                    <th scope="col">NOME</th>
                    <th scope="col">SOBRENOME</th>
                    <th scope="col">CEP</th>
                    <th scope="col">ENDEREÇO</th>
                    <th scope="col">CIDADE</th>
                    <th scope="col">EMAIL</th>
                    <th scope="col">TELEFONE</th>
                    <th scope="col">DATA REGISTRO</th>
                    <th scope="col">PERFIL</th>
                </tr>
            </thead>
            <tbody>
                {% for record in records %}
                    <tr>
                        <td>{{ record.nome }}</td>
                        <td>{{ record.sobrenome }}</td>
                        <td>{{ record.cep }}</td>
                        <td>{{ record.logradouro }}</td>
                        <td>{{ record.cidade }}</td>
                        <td>{{ record.email }}</td>
                        <td>{{ record.telefone }}</td>
                        <td>{{ record.created_at }}</td>
                        <td>
                            <a href="{% url 'record' record.id %}">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-person-rolodex mx-auto" viewBox="0 0 16 16">
                                    <path d="M8 9.05a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5"/>
                                    <path d="M1 1a1 1 0 0 0-1 1v11a1 1 0 0 0 1 1h.5a.5.5 0 0 0 .5-.5.5.5 0 0 1 1 0 .5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5.5.5 0 0 1 1 0 .5.5 0 0 0 .5.5h.5a1 1 0 0 0 1-1V3a1 1 0 0 0-1-1H6.707L6 1.293A1 1 0 0 0 5.293 1zm0 1h4.293L6 2.707A1 1 0 0 0 6.707 3H15v10h-.085a1.5 1.5 0 0 0-2.4-.63C11.885 11.223 10.554 10 8 10c-2.555 0-3.886 1.224-4.514 2.37a1.5 1.5 0 0 0-2.4.63H1z"/>
                                </svg>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="col-md-4 offset-md-4 ">
            <h1 class="text-center red">Login</h1>
            <br/>
            <form method="POST" action="{% url 'home' %}">
                {% csrf_token %}
                <div class="mb-3">
                    <input type="text" class="form-control" name="username" placeholder="Usuário:" required>
                </div>
                <div class="mb-3 ">
                    <input type="password" class="form-control" name="password" placeholder="Senha:" required>
                </div>
                <div class="mb-3 form-check ">
                    <input type="checkbox" class="form-check-input" id="exampleCheck1">
                    <label class="form-check-label" for="exampleCheck1">Lembrar-me</label>
                </div>
                <div class=" text-center">
                <button type="submit" class="mb-4 btn btn-secondary text-center">Entrar</button>
                    </br>
                    <a class="mb-4   btn btn-secondary" href="{%url 'register'%}">Registre-se</a>
                </div>
            </form>
        </div>
    {% endif %}
{% endblock %}

pythonProject/projeto_estoque/app_estoque/templates/usuario/navbar.html
<nav class="navbar bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand text-white " href="{% url 'home' %}">Controle de Funcionarios</a>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="btn  text-white " href="{%url 'home'%}" ><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house-door-fill" viewBox="0 0 16 16">
  <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5"/>
</svg></a>
          <a class="btn text-white" href="{%url 'logout'%}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-door-open-fill" viewBox="0 0 16 16">
  <path d="M1.5 15a.5.5 0 0 0 0 1h13a.5.5 0 0 0 0-1H13V2.5A1.5 1.5 0 0 0 11.5 1H11V.5a.5.5 0 0 0-.57-.495l-7 1A.5.5 0 0 0 3 1.5V15zM11 2h.5a.5.5 0 0 1 .5.5V15h-1zm-2.5 8c-.276 0-.5-.448-.5-1s.224-1 .5-1 .5.448.5 1-.224 1-.5 1"/>
</svg></a>
        </li>
        {%else%}
        <a class="nav-link" href="{%url 'home'%}">login</a>
        {%endif%}
    </div>
</nav>

pythonProject/projeto_estoque/app_estoque/templates/usuario/record.html
{% extends 'usuario/base.html' %}

{% block content %}
    <div class="card">
        <div class="card-header text-uppercase">
            <strong >Dados do Colaborador</strong>
        </div>
        <div class="card-body">
            <h5 class="card-title text-uppercase"><strong>{{customer_record.nome}} {{customer_record.sobrenome}}</strong></h5>
            <br/>
            <p class="card-text">
                <strong class="text-uppercase">Email: </strong>{{customer_record.email}} <br/>
            </p>
            <p class="card-text">
                <strong class="text-uppercase">Endereço: </strong>{{customer_record.logradouro}} <br/>
            </p>
            <p class="card-text">
                <strong class="text-uppercase">Cidade: </strong>{{customer_record.cidade}} <br/>
            </p>
            <p class="card-text">
                <strong class="text-uppercase">Uf: </strong>{{customer_record.estado}} <br/>
            </p>
            <p class="card-text">
                <strong class="text-uppercase">CEP: </strong>{{customer_record.cep}} <br/>
            </p>
            <p class="card-text">
                <strong class="text-uppercase">Telefone: </strong>{{customer_record.telefone}} <br/>
            </p>

            <p class="card-text">
                <strong class="text-uppercase"> Data Início: </strong>{{customer_record.created_at}} <br/>
            </p>
        </div>
        <br/><br/>



    </div>
        <a href="{% url 'update_record' customer_record.id %}" class="btn btn-secondary"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
  <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
  <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z"/>
</svg></a>
        <a href="{% url 'delete_record' customer_record.id %}" class="btn btn-danger"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
          <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5M8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5m3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0"/>
        </svg></a>
                <a href="{% url 'home' %}" class="btn btn-secondary"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-return-left" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M14.5 1.5a.5.5 0 0 1 .5.5v4.8a2.5 2.5 0 0 1-2.5 2.5H2.707l3.347 3.346a.5.5 0 0 1-.708.708l-4.2-4.2a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 8.3H12.5A1.5 1.5 0 0 0 14 6.8V2a.5.5 0 0 1 .5-.5"/>
        </svg></a>

{% endblock %}

pythonProject/projeto_estoque/app_estoque/templates/usuario/register.html
{% extends 'usuario/base.html' %}
{% block content %}

<div class="col-md-6 offset-md-3">
    <h1>Cadastro de Usuário</h1>
    <br/>
    <form method="POST" action="">
        {% csrf_token %}
        {% if form.errors %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                Seu formulário possui erros:
                {% for field in form %}
                    {% if field.errors %}
                        {{ field.errors }}
                    {% endif %}
                {% endfor %}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endif %}
        {{ form.as_p }}
        <br/>
        <button type="submit" class="btn btn-secondary">Registrar</button>
    </form>
</div>

{% endblock %}

pythonProject/projeto_estoque/app_estoque/templates/usuario/update_record.html
{% extends 'usuario/base.html' %}
{% block content %}
<div class="col-md-6 offset-md-3">
    <h1>Editar Dados</h1>
    <br/>
    <form method="POST">
            {% csrf_token %}

            {{ form.as_p }}
        <br/>


        <button type="submit" class="btn btn-secondary" >Editar</button>
        <a href="{% url 'home' %}" class="btn btn-secondary"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-return-left" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M14.5 1.5a.5.5 0 0 1 .5.5v4.8a2.5 2.5 0 0 1-2.5 2.5H2.707l3.347 3.346a.5.5 0 0 1-.708.708l-4.2-4.2a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 8.3H12.5A1.5 1.5 0 0 0 14 6.8V2a.5.5 0 0 1 .5-.5"/>
</svg></a>
    </form>
          <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script>
        $(document).ready(function() {
            $('#id_cep').change(function() {
                var cep = $(this).val();
                $.ajax({
                    url: 'https://viacep.com.br/ws/' + cep + '/json/',
                    dataType: 'json',
                    success: function(data) {
                        $('#id_logradouro').val(data.logradouro);
                        $('#id_bairro').val(data.bairro);
                        $('#id_cidade').val(data.localidade);
                        $('#id_estado').val(data.uf);
                    }
                });
            });
        });
        </script>
</div>

{% endblock %}